# Generated by Django 3.2.9 on 2021-12-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='qr_code',
        ),
    ]
